---
services:
  - docker

notifications:
  email: false

addons:
  apt:
    packages:
      - docker-ce

env:
  - DOCKER_COMPOSE_VERSION=1.25.5

branches:
  only:
    - master

before_install: ./scripts/ci/upgrade_docker_compose.sh

install: true

script: ./scripts/ci/build.sh
